### ISSUE TITLE
Error in TLS Handshake

### ISSUE THREAD

**Issue by Hans-HDA** [exyi/pg2parquet#17]
Hi Standa, hope you do not mind creating an issue for a quesion I have regarding your pg2parquet tool. I would love to export my data from PSQL to Parquet what your tool offers. However, when trying to use it, I get the following error:

`DB connection failed: error performing TLS handshake: The certificate's CN name does not match the passed value. (os error -2146762481)`

I have tried all SSL modes but without any results. Do you have any suggestions how to fix this?

Thanks in advance, 

Hans

**Comment by Hans-HDA** [comment]
Hi Standa, the issue is not relevant anymore. In the original request, I used the IP number of the PSQL server. However, when using the DNS name, I did not get a TLS error. So all good and sorry for bothering you.

**Comment by exyi** [comment]
No problem! Yes, you have to use the domain name which is in the servers certificate, otherwise TLS cannot verify that the certificate is authentic
