### ISSUE TITLE
Support of custom CAs to deal with self-signed certificates

### ISSUE THREAD

**Issue by moritz93** [exyi/pg2parquet#20]
If the PG server uses a self-signed certificate, `sslmode=require` is not supported. It would be nice to have an option to pass a custom root CA (https://docs.rs/openssl/0.9.24/openssl/ssl/struct.SslContextBuilder.html#method.set_ca_file).

**Comment by exyi** [comment]
Hi! I have added the option in #21, could you please verify that it works for you? You can run the development version using the following commands:

```
git clone https://github.com/exyi/pg2parquet.git
cd pg2parquet/cli
git switch ssl-root-cert
cargo run -- export {your options}
```

**Comment by moritz93** [comment]
Works, thanks a lot!

**Comment by exyi** [comment]
Thanks a lot for testing it for me :) I have release it as the 0.1.0 version.
