### ISSUE TITLE
GH workflows aren't uploading all artifacts

### ISSUE THREAD

**Issue by piraka9011** [exyi/pg2parquet#6]
See any of the runs and notice only one system artifact is created.
The logs for the upload-artifact action show

```
No files were found with the provided path: output_dir/pg2parquet. No artifacts will be uploaded.
```

I also can't install this from cargo:

```sh
$ cargo install pg2parquet

    Updating crates.io index
error: could not find `pg2parquet` in registry `crates-io` with version `*`
```

**Comment by exyi** [comment]
Thanks for reporting, I think I fixed it here https://github.com/exyi/pg2parquet/actions/runs/5558341715

I published it as a beta version and apparently cargo requires to explicitly specify the version to install a preview:

```
cargo install pg2parquet@0.1.0-beta.3
```

**Comment by piraka9011** [comment]
Nice, thanks for the quick turn around!

I had to run `sudo apt install build-essential` on an Ubuntu 22.04 machine to run the cargo install (`libm` and other packages had to be compiled).

Will test this package out since it seems to solve for some post-processing work we'd like to do on our postgres tables.
